In [1]:
import numpy as np
import pandas as pd

scores = pd.DataFrame(np.random.randint(50,101,size=(50,5)),
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index=range(1,51))
scores

    國文   英文  數學   地理  歷史
1   50   58  90   93  78
2   75   58  96   95  54
3   58   57  91   76  78
4   94   93  88   79  91
5   71   79  92   55  70
6   66   82  89   85  79
7   95   90  85   54  68
8   97   73  59   89  74
9   59   56  91   80  83
10  72   72  93   52  62
11  92   79  91   81  55
12  78   65  92   55  50
13  57   55  83   63  83
14  87   99  52   66  83
15  91   89  86   88  60
16  54   92  88   65  53
17  54   94  82   60  99
18  54   99  70   64  73
19  87   71  66   87  75
20  74   64  63   69  74
21  66   89  95   71  98
22  71   78  82   96  58
23  88  100  75   63  50
24  99   82  92   97  51
25  92   84  50   97  63
26  54   96  96   69  69
27  50   95  95  100  57
28  64   62  89   55  86
29  92   53  68   70  57
30  68   50  63   68  78
31  69   84  58   83  89
32  70   84  66   85  79
33  88   79  86   64  99
34  88   55  94   82  85
35  89   76  56   79  98
36  75   68  51   59  75
37  82   83  68   52  84
38  79   65  98   50  92
39  63   52  58   70  74
40  72   88  59   71  73
41  75  100  74   70  67
42  65   56  61   90  65
43  64   62  92   96  65
44  97   77  55   74  62
45  75   65  55   98  68
46  66   84  84   66  63
47  72   74  85   59  92
48  90   94  88   52  52
49  66   91  87   74  91
50  60   67  95   52  76

In [2]:
def abc(s):
    return s.max()
scores.apply(abc)

國文     99
英文    100
數學     98
地理    100
歷史     99
dtype: int64

In [3]:
def abc(s):
    return pd.Series([s.min(),s.max(),s.mean()],index=['最低分','最高分','平均'])
scores.apply(abc)

        國文      英文     數學      地理     歷史
最低分  50.00   50.00  50.00   50.00  50.00
最高分  99.00  100.00  98.00  100.00  99.00
平均   74.28   76.36  78.44   73.36  73.16

In [4]:
scores.index = scores.index.map(lambda i:f'{i}號')
scores

     國文   英文  數學   地理  歷史
1號   50   58  90   93  78
2號   75   58  96   95  54
3號   58   57  91   76  78
4號   94   93  88   79  91
5號   71   79  92   55  70
6號   66   82  89   85  79
7號   95   90  85   54  68
8號   97   73  59   89  74
9號   59   56  91   80  83
10號  72   72  93   52  62
11號  92   79  91   81  55
12號  78   65  92   55  50
13號  57   55  83   63  83
14號  87   99  52   66  83
15號  91   89  86   88  60
16號  54   92  88   65  53
17號  54   94  82   60  99
18號  54   99  70   64  73
19號  87   71  66   87  75
20號  74   64  63   69  74
21號  66   89  95   71  98
22號  71   78  82   96  58
23號  88  100  75   63  50
24號  99   82  92   97  51
25號  92   84  50   97  63
26號  54   96  96   69  69
27號  50   95  95  100  57
28號  64   62  89   55  86
29號  92   53  68   70  57
30號  68   50  63   68  78
31號  69   84  58   83  89
32號  70   84  66   85  79
33號  88   79  86   64  99
34號  88   55  94   82  85
35號  89   76  56   79  98
36號  75   68  51   59  75
37號  82   83  68   52  84
38號  79   65  98   50  92
39號  63   52  58   70  74
40號  72   88  59   71  73
41號  75  100  74   70  67
42號  65   56  61   90  65
43號  64   62  92   96  65
44號  97   77  55   74  62
45號  75   65  55   98  68
46號  66   84  84   66  63
47號  72   74  85   59  92
48號  90   94  88   52  52
49號  66   91  87   74  91
50號  60   67  95   52  76

In [5]:
def abc1(item):
    return pd.Series([item.sum(),item.mean()],index=['總分','平均'])
scores.apply(abc1,axis=1)

        總分    平均
1號   369.0  73.8
2號   378.0  75.6
3號   360.0  72.0
4號   445.0  89.0
5號   367.0  73.4
6號   401.0  80.2
7號   392.0  78.4
8號   392.0  78.4
9號   369.0  73.8
10號  351.0  70.2
11號  398.0  79.6
12號  340.0  68.0
13號  341.0  68.2
14號  387.0  77.4
15號  414.0  82.8
16號  352.0  70.4
17號  389.0  77.8
18號  360.0  72.0
19號  386.0  77.2
20號  344.0  68.8
21號  419.0  83.8
22號  385.0  77.0
23號  376.0  75.2
24號  421.0  84.2
25號  386.0  77.2
26號  384.0  76.8
27號  397.0  79.4
28號  356.0  71.2
29號  340.0  68.0
30號  327.0  65.4
31號  383.0  76.6
32號  384.0  76.8
33號  416.0  83.2
34號  404.0  80.8
35號  398.0  79.6
36號  328.0  65.6
37號  369.0  73.8
38號  384.0  76.8
39號  317.0  63.4
40號  363.0  72.6
41號  386.0  77.2
42號  337.0  67.4
43號  379.0  75.8
44號  365.0  73.0
45號  361.0  72.2
46號  363.0  72.6
47號  382.0  76.4
48號  376.0  75.2
49號  409.0  81.8
50號  350.0  70.0

In [6]:
one_student = scores.iloc[0]
less_student = one_student[one_student < 60]
less_student

國文    50
英文    58
Name: 1號, dtype: int64

In [7]:
less_student.count()
",".join(less_student.index.values.tolist())

'國文,英文'

In [8]:
def abc(s):
    return pd.Series([s.min(),s.max(),s.mean()],index=['最低分','最高分','平均'])
scores.apply(abc)

        國文      英文     數學      地理     歷史
最低分  50.00   50.00  50.00   50.00  50.00
最高分  99.00  100.00  98.00  100.00  99.00
平均   74.28   76.36  78.44   73.36  73.16

In [9]:
scores.index = scores.index.map(lambda i:f'{i}號')
scores

      國文   英文  數學   地理  歷史
1號號   50   58  90   93  78
2號號   75   58  96   95  54
3號號   58   57  91   76  78
4號號   94   93  88   79  91
5號號   71   79  92   55  70
6號號   66   82  89   85  79
7號號   95   90  85   54  68
8號號   97   73  59   89  74
9號號   59   56  91   80  83
10號號  72   72  93   52  62
11號號  92   79  91   81  55
12號號  78   65  92   55  50
13號號  57   55  83   63  83
14號號  87   99  52   66  83
15號號  91   89  86   88  60
16號號  54   92  88   65  53
17號號  54   94  82   60  99
18號號  54   99  70   64  73
19號號  87   71  66   87  75
20號號  74   64  63   69  74
21號號  66   89  95   71  98
22號號  71   78  82   96  58
23號號  88  100  75   63  50
24號號  99   82  92   97  51
25號號  92   84  50   97  63
26號號  54   96  96   69  69
27號號  50   95  95  100  57
28號號  64   62  89   55  86
29號號  92   53  68   70  57
30號號  68   50  63   68  78
31號號  69   84  58   83  89
32號號  70   84  66   85  79
33號號  88   79  86   64  99
34號號  88   55  94   82  85
35號號  89   76  56   79  98
36號號  75   68  51   59  75
37號號  82   83  68   52  84
38號號  79   65  98   50  92
39號號  63   52  58   70  74
40號號  72   88  59   71  73
41號號  75  100  74   70  67
42號號  65   56  61   90  65
43號號  64   62  92   96  65
44號號  97   77  55   74  62
45號號  75   65  55   98  68
46號號  66   84  84   66  63
47號號  72   74  85   59  92
48號號  90   94  88   52  52
49號號  66   91  87   74  91
50號號  60   67  95   52  76

In [10]:
def abc1(item):
    less_student = item[item < 60]
    less_count = less_student.count()
    less_str = ",".join(less_student.index.values.tolist())
    
    return pd.Series([item.sum(),item.mean(),less_count,less_str],index=['總分','平均','不及格科目數','不及格科目'])
scores.apply(abc1,axis=1)

       總分    平均  不及格科目數  不及格科目
1號號   369  73.8       2  國文,英文
2號號   378  75.6       2  英文,歷史
3號號   360  72.0       2  國文,英文
4號號   445  89.0       0
5號號   367  73.4       1     地理
6號號   401  80.2       0
7號號   392  78.4       1     地理
8號號   392  78.4       1     數學
9號號   369  73.8       2  國文,英文
10號號  351  70.2       1     地理
11號號  398  79.6       1     歷史
12號號  340  68.0       2  地理,歷史
13號號  341  68.2       2  國文,英文
14號號  387  77.4       1     數學
15號號  414  82.8       0
16號號  352  70.4       2  國文,歷史
17號號  389  77.8       1     國文
18號號  360  72.0       1     國文
19號號  386  77.2       0
20號號  344  68.8       0
21號號  419  83.8       0
22號號  385  77.0       1     歷史
23號號  376  75.2       1     歷史
24號號  421  84.2       1     歷史
25號號  386  77.2       1     數學
26號號  384  76.8       1     國文
27號號  397  79.4       2  國文,歷史
28號號  356  71.2       1     地理
29號號  340  68.0       2  英文,歷史
30號號  327  65.4       1     英文
31號號  383  76.6       1     數學
32號號  384  76.8       0
33號號  416  83.2       0
34號號  404  80.8       1     英文
35號號  398  79.6       1     數學
36號號  328  65.6       2  數學,地理
37號號  369  73.8       1     地理
38號號  384  76.8       1     地理
39號號  317  63.4       2  英文,數學
40號號  363  72.6       1     數學
41號號  386  77.2       0
42號號  337  67.4       1     英文
43號號  379  75.8       0
44號號  365  73.0       1     數學
45號號  361  72.2       1     數學
46號號  363  72.6       0
47號號  382  76.4       1     地理
48號號  376  75.2       2  地理,歷史
49號號  409  81.8       0
50號號  350  70.0       1     地理